# Generated by Django 5.2.6 on 2025-09-29 21:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Service categories',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('blurb', models.TextField(blank=True)),
                ('hero_image', models.URLField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='booknow.servicecategory')),
            ],
            options={
                'ordering': ('category__sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('address_line', models.CharField(max_length=200)),
                ('suburb', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=10)),
                ('postcode', models.CharField(max_length=10)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('frequency', models.CharField(choices=[('one_time', 'One-time'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly')], default='one_time', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booknow.service')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at'], name='booknow_boo_created_f13ee7_idx'), models.Index(fields=['status'], name='booknow_boo_status_46d0bf_idx'), models.Index(fields=['service'], name='booknow_boo_service_78935f_idx')],
            },
        ),
    ]
