# Generated by Django 5.2.6 on 2025-10-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booknow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='access_window',
            field=models.CharField(blank=True, help_text="e.g., 8–10am window or 'after 5pm'.", max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='parking_notes',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
