# Generated by Django 5.2.6 on 2025-10-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booknow', '0002_booking_access_window_booking_parking_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_estimate',
            field=models.IntegerField(blank=True, help_text='Estimated price in cents', null=True),
        ),
    ]
